### ISSUE TITLE
通过asyncio取分钟线的时候报错

### ISSUE THREAD

**Issue by gglive** [xingetouzi/rqalpha-mod-fxdayu-source#2]
弹出There is no current event loop in thread

参考如下连接修改后能正常运行了
[Link](https://stackoverflow.com/questions/46727787/runtimeerror-there-is-no-current-event-loop-in-thread-in-async-apscheduler)

**Comment by BurdenBear** [comment]
感谢提交bug和solution。
尝试按照link中间提到的方法修复了一下，运行时new_event_loop也只会调用一次，应该不会引入额外开销。有些机器上跑会出这个错误，有些不会 :( 。 也可能是asyncio那一块没写好，有时间再仔细看看。
